stages:
  - build

build_job:
  tags:
    - windows
  stage: build
  script:
    - 'C:\Tools\Nuget\nuget.exe restore'
    - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild.exe"'
    - 'packages\NUnit.ConsoleRunner.3.10.0\tools\nunit3-console.exe'