variables:  
  NUGET: 'C:\Tools\Nuget\nuget.exe'
  MSBUILD: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild.exe'
  NUNIT: packages\NUnit.ConsoleRunner.3.10.0\tools\nunit3-console.exe
  
stages:
  - build

build_job:
  tags:
    - windows
  stage: build
  script:
    - '& "$env:NUGET" restore'
    - '& "$env:MSBUILD" /p:Configuration=Release /clp:WarningsOnly'
    - '& "$env:NUNIT" Source\TcxEditor.Core.Tests\bin\Release\TcxEditor.Core.Tests.dll Source\TcxParser.Tests\bin\Release\TcxParser.Tests.dll'